language: go
go: 1.1
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/fd/go-shellwords/shellwords
  - go get github.com/garyburd/redigo/redis
  - go get github.com/lib/pq
  - go get github.com/go-sql-driver/mysql
  - go get github.com/ziutek/mymysql/mysql
  - go get github.com/ziutek/mymysql/native
  - go get github.com/ziutek/mymysql/godrv
  - go get github.com/mattn/go-sqlite3
services:
  - redis-server
  - postgres 
  - mysql

before_script:
  - psql -c "CREATE USER tpt WITH PASSWORD 'extreme';" -U postgres
  - psql -c "create database tpt_data with OWNER = tpt;" -U postgres
  - mysql -e "CREATE USER 'tpt' IDENTIFIED BY 'extreme';"
  - mysql -e "create database tpt_data;"
script:
  - go test -v
  - go test -v -test_db_drv=mysql -test_db_url="travis:@tcp(localhost:3306)/tpt_data?autocommit=true&parseTime=true" -test.run=DbHandler
  - go test -v -test_db_drv=mymysql -test_db_url=tcp:127.0.0.1:3306*tpt_data/travis/  -test.run=DbHandler
  - go test -v -db_drv=mymysql -db_url=tcp:127.0.0.1:3306*tpt_data/travis/
  - go test -v -db_drv=mymysql -db_url=tcp:127.0.0.1:3306*tpt_data/travis/  -test_db_drv=mysql -test_db_url="travis:@tcp(localhost:3306)/tpt_data?autocommit=true&parseTime=true" -test.run=DbHandler
  - go test -v -db_drv=mymysql -db_url=tcp:127.0.0.1:3306*tpt_data/travis/ -test_db_drv=postgres -test_db_url="host=127.0.0.1 dbname=tpt_data user=tpt password=extreme sslmode=disable"  -test.run=DbHandler
  - go test -v -db_drv=mysql -db_url="travis:@tcp(localhost:3306)/tpt_data?autocommit=true&parseTime=true"
  - go test -v -db_drv=mysql -db_url="travis:@tcp(localhost:3306)/tpt_data?autocommit=true&parseTime=true" -test_db_drv=mymysql -test_db_url=tcp:127.0.0.1:3306*tpt_data/travis/  -test.run=DbHandler
  - go test -v -db_drv=mysql -db_url="travis:@tcp(localhost:3306)/tpt_data?autocommit=true&parseTime=true" -test_db_drv=postgres -test_db_url="host=127.0.0.1 dbname=tpt_data user=tpt password=extreme sslmode=disable"  -test.run=DbHandler
