language: go
go: 1.1
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/fd/go-shellwords/shellwords
  - go get github.com/garyburd/redigo/redis
  - go get github.com/lib/pq
  - go get github.com/go-sql-driver/mysql
  - go get github.com/mattn/go-sqlite3
services:
  - redis-server
  - postgres 
  - mysql

before_script:
  - psql -c "CREATE USER tpt WITH PASSWORD 'extreme';" -U postgres
  - psql -c "create database tpt_data with OWNER = tpt;" -U postgres
  - mysql -e "CREATE USER 'tpt' IDENTIFIED BY 'extreme';"
  - mysql -e "create database tpt_data;"
script:
  - go test -v
  - go test -v -db_drv=mymysql -db_url=tcp:127.0.0.1:3306*tpt_data/travis
  - go test -v -db_drv=mysql -db_url="travis:@tcp(localhost:3306)/tpt_data?autocommit=true&parseTime=true"
